#!/usr/bin/env bash
# Deploy script for journey.zad.tools (static Nuxt build) on CloudPanel
# Generated by skill: cloudpanel-deploy-script
set -euo pipefail

# ─── Config ───────────────────────────────────────────────
REMOTE_USER="root"
REMOTE_HOST="157.180.43.248"
REMOTE_PATH="/home/journey/htdocs/journey.zad.tools"
SITE_USER="journey"
LOCAL_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${LOCAL_PATH}/.output/public"
SSH_KEY="${HOME}/.ssh/cp_server"

# ─── Colors ───────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'; NC='\033[0m'
ok()   { echo -e "${GRN}✓${NC} $1"; }
warn() { echo -e "${YLW}!${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1" >&2; }

# ─── Args ─────────────────────────────────────────────────
DRY_RUN=0; ROLLBACK=0; SKIP_BUILD=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run|-n)   DRY_RUN=1; shift ;;
    --rollback)     ROLLBACK=1; shift ;;
    --skip-build)   SKIP_BUILD=1; shift ;;
    --help|-h)
      cat <<EOF
Usage: ./deploy.sh [OPTIONS]
  -n, --dry-run     Show what would change, don't transfer
      --skip-build  Deploy the existing .output/public without rebuilding
      --rollback    Restore previous deploy from remote backup
  -h, --help        This help
EOF
      exit 0 ;;
    *) err "Unknown arg: $1"; exit 1 ;;
  esac
done

# ─── Pre-flight ───────────────────────────────────────────
command -v rsync >/dev/null || { err "rsync not installed"; exit 1; }
ssh -i "$SSH_KEY" -o BatchMode=yes "${REMOTE_USER}@${REMOTE_HOST}" true 2>/dev/null \
  || { err "SSH connection failed"; exit 1; }
ok "SSH OK"

# ─── Rollback ─────────────────────────────────────────────
if [[ $ROLLBACK -eq 1 ]]; then
  LATEST=$(ssh -i "$SSH_KEY" "${REMOTE_USER}@${REMOTE_HOST}" "ls -t ~/.deploy-backups/journey.zad.tools-*.tar.gz 2>/dev/null | head -1")
  [[ -z "$LATEST" ]] && { err "No backups found"; exit 1; }
  warn "Restoring $LATEST"
  ssh -i "$SSH_KEY" "${REMOTE_USER}@${REMOTE_HOST}" \
    "rm -rf ${REMOTE_PATH} && tar -xzf $LATEST -C $(dirname "$REMOTE_PATH") && chown -R ${SITE_USER}:${SITE_USER} ${REMOTE_PATH}"
  ok "Rollback complete"
  exit 0
fi

# ─── Build (root base — the custom domain serves from /) ──
if [[ $SKIP_BUILD -eq 0 ]]; then
  warn "Building static site…"
  (cd "$LOCAL_PATH" && bun run generate >/dev/null)
  ok "Build complete"
fi
[[ -f "${BUILD_DIR}/index.html" ]] || { err "No build at ${BUILD_DIR} — run without --skip-build"; exit 1; }

# ─── Backup (remote → ~/.deploy-backups) ──────────────────
if [[ $DRY_RUN -eq 0 ]]; then
  TS=$(date +%Y%m%d-%H%M%S)
  ssh -i "$SSH_KEY" "${REMOTE_USER}@${REMOTE_HOST}" \
    "mkdir -p ~/.deploy-backups && tar -czf ~/.deploy-backups/journey.zad.tools-${TS}.tar.gz -C $(dirname "$REMOTE_PATH") $(basename "$REMOTE_PATH") 2>/dev/null || true; ls -t ~/.deploy-backups/journey.zad.tools-*.tar.gz | tail -n +6 | xargs rm -f 2>/dev/null || true"
  ok "Remote backup created (keeping last 5)"
fi

# ─── Sync ─────────────────────────────────────────────────
RSYNC_FLAGS=(-az --delete)
[[ $DRY_RUN -eq 1 ]] && RSYNC_FLAGS+=(--dry-run --itemize-changes)
rsync "${RSYNC_FLAGS[@]}" -e "ssh -i $SSH_KEY" \
  "${BUILD_DIR}/" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"
ok "Synced"

# ─── Post-deploy: ownership + smoke test ──────────────────
if [[ $DRY_RUN -eq 0 ]]; then
  ssh -i "$SSH_KEY" "${REMOTE_USER}@${REMOTE_HOST}" "chown -R ${SITE_USER}:${SITE_USER} ${REMOTE_PATH}"
  CODE=$(curl -s -o /dev/null -w "%{http_code}" https://journey.zad.tools/)
  [[ "$CODE" == "200" ]] && ok "Live check: https://journey.zad.tools → 200" || err "Live check returned $CODE"
fi

ok "Deploy complete"
